# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bkaboa/Documents/my_42_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bkaboa/Documents/my_42_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bkaboa/Documents/my_42_lib/CMakeFiles /home/bkaboa/Documents/my_42_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bkaboa/Documents/my_42_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/build
.PHONY : ft/fast

#=============================================================================
# Target rules for targets named opt

# Build rule for target.
opt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opt
.PHONY : opt

# fast build rule for target.
opt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opt.dir/build.make CMakeFiles/opt.dir/build
.PHONY : opt/fast

libft/ft_atoi.o: libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.o

# target to build an object file
libft/ft_atoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.c.o

libft/ft_atoi.i: libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.i

# target to preprocess a source file
libft/ft_atoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.c.i

libft/ft_atoi.s: libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.s

# target to generate assembly for a file
libft/ft_atoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.c.s

libft/ft_is.o: libft/ft_is.c.o
.PHONY : libft/ft_is.o

# target to build an object file
libft/ft_is.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_is.c.o
.PHONY : libft/ft_is.c.o

libft/ft_is.i: libft/ft_is.c.i
.PHONY : libft/ft_is.i

# target to preprocess a source file
libft/ft_is.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_is.c.i
.PHONY : libft/ft_is.c.i

libft/ft_is.s: libft/ft_is.c.s
.PHONY : libft/ft_is.s

# target to generate assembly for a file
libft/ft_is.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_is.c.s
.PHONY : libft/ft_is.c.s

libft/ft_memcmp.o: libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.o

# target to build an object file
libft/ft_memcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.c.o

libft/ft_memcmp.i: libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.i

# target to preprocess a source file
libft/ft_memcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.c.i

libft/ft_memcmp.s: libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.s

# target to generate assembly for a file
libft/ft_memcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.c.s

libft/ft_memcpy.o: libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.o

# target to build an object file
libft/ft_memcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.c.o

libft/ft_memcpy.i: libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.i

# target to preprocess a source file
libft/ft_memcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.c.i

libft/ft_memcpy.s: libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.s

# target to generate assembly for a file
libft/ft_memcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.c.s

libft/ft_memset.o: libft/ft_memset.c.o
.PHONY : libft/ft_memset.o

# target to build an object file
libft/ft_memset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memset.c.o
.PHONY : libft/ft_memset.c.o

libft/ft_memset.i: libft/ft_memset.c.i
.PHONY : libft/ft_memset.i

# target to preprocess a source file
libft/ft_memset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memset.c.i
.PHONY : libft/ft_memset.c.i

libft/ft_memset.s: libft/ft_memset.c.s
.PHONY : libft/ft_memset.s

# target to generate assembly for a file
libft/ft_memset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_memset.c.s
.PHONY : libft/ft_memset.c.s

libft/ft_putchar.o: libft/ft_putchar.c.o
.PHONY : libft/ft_putchar.o

# target to build an object file
libft/ft_putchar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putchar.c.o
.PHONY : libft/ft_putchar.c.o

libft/ft_putchar.i: libft/ft_putchar.c.i
.PHONY : libft/ft_putchar.i

# target to preprocess a source file
libft/ft_putchar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putchar.c.i
.PHONY : libft/ft_putchar.c.i

libft/ft_putchar.s: libft/ft_putchar.c.s
.PHONY : libft/ft_putchar.s

# target to generate assembly for a file
libft/ft_putchar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putchar.c.s
.PHONY : libft/ft_putchar.c.s

libft/ft_putstr.o: libft/ft_putstr.c.o
.PHONY : libft/ft_putstr.o

# target to build an object file
libft/ft_putstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putstr.c.o
.PHONY : libft/ft_putstr.c.o

libft/ft_putstr.i: libft/ft_putstr.c.i
.PHONY : libft/ft_putstr.i

# target to preprocess a source file
libft/ft_putstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putstr.c.i
.PHONY : libft/ft_putstr.c.i

libft/ft_putstr.s: libft/ft_putstr.c.s
.PHONY : libft/ft_putstr.s

# target to generate assembly for a file
libft/ft_putstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_putstr.c.s
.PHONY : libft/ft_putstr.c.s

libft/ft_realloc.o: libft/ft_realloc.c.o
.PHONY : libft/ft_realloc.o

# target to build an object file
libft/ft_realloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_realloc.c.o
.PHONY : libft/ft_realloc.c.o

libft/ft_realloc.i: libft/ft_realloc.c.i
.PHONY : libft/ft_realloc.i

# target to preprocess a source file
libft/ft_realloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_realloc.c.i
.PHONY : libft/ft_realloc.c.i

libft/ft_realloc.s: libft/ft_realloc.c.s
.PHONY : libft/ft_realloc.s

# target to generate assembly for a file
libft/ft_realloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_realloc.c.s
.PHONY : libft/ft_realloc.c.s

libft/ft_strcat.o: libft/ft_strcat.c.o
.PHONY : libft/ft_strcat.o

# target to build an object file
libft/ft_strcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcat.c.o
.PHONY : libft/ft_strcat.c.o

libft/ft_strcat.i: libft/ft_strcat.c.i
.PHONY : libft/ft_strcat.i

# target to preprocess a source file
libft/ft_strcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcat.c.i
.PHONY : libft/ft_strcat.c.i

libft/ft_strcat.s: libft/ft_strcat.c.s
.PHONY : libft/ft_strcat.s

# target to generate assembly for a file
libft/ft_strcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcat.c.s
.PHONY : libft/ft_strcat.c.s

libft/ft_strcmp.o: libft/ft_strcmp.c.o
.PHONY : libft/ft_strcmp.o

# target to build an object file
libft/ft_strcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcmp.c.o
.PHONY : libft/ft_strcmp.c.o

libft/ft_strcmp.i: libft/ft_strcmp.c.i
.PHONY : libft/ft_strcmp.i

# target to preprocess a source file
libft/ft_strcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcmp.c.i
.PHONY : libft/ft_strcmp.c.i

libft/ft_strcmp.s: libft/ft_strcmp.c.s
.PHONY : libft/ft_strcmp.s

# target to generate assembly for a file
libft/ft_strcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strcmp.c.s
.PHONY : libft/ft_strcmp.c.s

libft/ft_strdup.o: libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.o

# target to build an object file
libft/ft_strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.c.o

libft/ft_strdup.i: libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.i

# target to preprocess a source file
libft/ft_strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.c.i

libft/ft_strdup.s: libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.s

# target to generate assembly for a file
libft/ft_strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.c.s

libft/ft_strjoin.o: libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.o

# target to build an object file
libft/ft_strjoin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.c.o

libft/ft_strjoin.i: libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.i

# target to preprocess a source file
libft/ft_strjoin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.c.i

libft/ft_strjoin.s: libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.s

# target to generate assembly for a file
libft/ft_strjoin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.c.s

libft/ft_strlen.o: libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.o

# target to build an object file
libft/ft_strlen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.c.o

libft/ft_strlen.i: libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.i

# target to preprocess a source file
libft/ft_strlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.c.i

libft/ft_strlen.s: libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.s

# target to generate assembly for a file
libft/ft_strlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.c.s

libft/ft_swap.o: libft/ft_swap.c.o
.PHONY : libft/ft_swap.o

# target to build an object file
libft/ft_swap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_swap.c.o
.PHONY : libft/ft_swap.c.o

libft/ft_swap.i: libft/ft_swap.c.i
.PHONY : libft/ft_swap.i

# target to preprocess a source file
libft/ft_swap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_swap.c.i
.PHONY : libft/ft_swap.c.i

libft/ft_swap.s: libft/ft_swap.c.s
.PHONY : libft/ft_swap.s

# target to generate assembly for a file
libft/ft_swap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_swap.c.s
.PHONY : libft/ft_swap.c.s

libft/ft_to.o: libft/ft_to.c.o
.PHONY : libft/ft_to.o

# target to build an object file
libft/ft_to.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_to.c.o
.PHONY : libft/ft_to.c.o

libft/ft_to.i: libft/ft_to.c.i
.PHONY : libft/ft_to.i

# target to preprocess a source file
libft/ft_to.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_to.c.i
.PHONY : libft/ft_to.c.i

libft/ft_to.s: libft/ft_to.c.s
.PHONY : libft/ft_to.s

# target to generate assembly for a file
libft/ft_to.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/libft/ft_to.c.s
.PHONY : libft/ft_to.c.s

optLib/ft_getopt.o: optLib/ft_getopt.c.o
.PHONY : optLib/ft_getopt.o

# target to build an object file
optLib/ft_getopt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opt.dir/build.make CMakeFiles/opt.dir/optLib/ft_getopt.c.o
.PHONY : optLib/ft_getopt.c.o

optLib/ft_getopt.i: optLib/ft_getopt.c.i
.PHONY : optLib/ft_getopt.i

# target to preprocess a source file
optLib/ft_getopt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opt.dir/build.make CMakeFiles/opt.dir/optLib/ft_getopt.c.i
.PHONY : optLib/ft_getopt.c.i

optLib/ft_getopt.s: optLib/ft_getopt.c.s
.PHONY : optLib/ft_getopt.s

# target to generate assembly for a file
optLib/ft_getopt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opt.dir/build.make CMakeFiles/opt.dir/optLib/ft_getopt.c.s
.PHONY : optLib/ft_getopt.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft"
	@echo "... opt"
	@echo "... libft/ft_atoi.o"
	@echo "... libft/ft_atoi.i"
	@echo "... libft/ft_atoi.s"
	@echo "... libft/ft_is.o"
	@echo "... libft/ft_is.i"
	@echo "... libft/ft_is.s"
	@echo "... libft/ft_memcmp.o"
	@echo "... libft/ft_memcmp.i"
	@echo "... libft/ft_memcmp.s"
	@echo "... libft/ft_memcpy.o"
	@echo "... libft/ft_memcpy.i"
	@echo "... libft/ft_memcpy.s"
	@echo "... libft/ft_memset.o"
	@echo "... libft/ft_memset.i"
	@echo "... libft/ft_memset.s"
	@echo "... libft/ft_putchar.o"
	@echo "... libft/ft_putchar.i"
	@echo "... libft/ft_putchar.s"
	@echo "... libft/ft_putstr.o"
	@echo "... libft/ft_putstr.i"
	@echo "... libft/ft_putstr.s"
	@echo "... libft/ft_realloc.o"
	@echo "... libft/ft_realloc.i"
	@echo "... libft/ft_realloc.s"
	@echo "... libft/ft_strcat.o"
	@echo "... libft/ft_strcat.i"
	@echo "... libft/ft_strcat.s"
	@echo "... libft/ft_strcmp.o"
	@echo "... libft/ft_strcmp.i"
	@echo "... libft/ft_strcmp.s"
	@echo "... libft/ft_strdup.o"
	@echo "... libft/ft_strdup.i"
	@echo "... libft/ft_strdup.s"
	@echo "... libft/ft_strjoin.o"
	@echo "... libft/ft_strjoin.i"
	@echo "... libft/ft_strjoin.s"
	@echo "... libft/ft_strlen.o"
	@echo "... libft/ft_strlen.i"
	@echo "... libft/ft_strlen.s"
	@echo "... libft/ft_swap.o"
	@echo "... libft/ft_swap.i"
	@echo "... libft/ft_swap.s"
	@echo "... libft/ft_to.o"
	@echo "... libft/ft_to.i"
	@echo "... libft/ft_to.s"
	@echo "... optLib/ft_getopt.o"
	@echo "... optLib/ft_getopt.i"
	@echo "... optLib/ft_getopt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

